# Generated by Django 5.0.7 on 2024-09-22 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sistemaventas',
            name='venta_total',
        ),
    ]
