# Generated by Django 5.0.7 on 2024-09-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0002_remove_sistemaventas_venta_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemaventas',
            name='venta_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
