# Generated by Django 5.0.7 on 2024-09-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0003_sistemaventas_venta_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemaventas',
            name='codigo_venta',
            field=models.CharField(default=0, editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='sistemaventas',
            name='venta_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
