# Generated by Django 5.0.7 on 2024-09-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0004_sistemaventas_codigo_venta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemaventas',
            name='codigo_venta',
            field=models.CharField(default=0, editable=False, max_length=10, unique=True),
        ),
    ]
